### ISSUE TITLE
gs have undercover resolver? 

### ISSUE THREAD

**Issue by hapi-dev** [rbelsha/gamesense.pub#2]
ok

**Comment by rbelsha** [comment]
![esotk_upload1](https://user-images.githubusercontent.com/65768277/114254515-8108e800-9975-11eb-8fa4-50fe37a17626.png)
![gamesense-pub](https://user-images.githubusercontent.com/65768277/114254548-a695f180-9975-11eb-8bb2-dd2ce0610cf9.png)
